In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [57]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [58]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [59]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [60]:
df.shape

(5572, 3)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test , y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [63]:
X_train.shape

(4457,)

In [64]:
X_test.shape

(1115,)

In [65]:
type(X_train)

pandas.core.series.Series

In [66]:
X_train[0:5]

105          Umma my life and vava umma love you lot dear
534                                       I'll be late...
2838                              1's reach home call me.
5457                          Arun can u transfr me d amt
4619    Nvm... I'm going to wear my sport shoes anyway...
Name: Message, dtype: object

In [68]:
y_train[0:5]

105     0
534     0
2838    0
5457    0
4619    0
Name: spam, dtype: int64

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

In [70]:
X_train.values #numpy array

array(['Umma my life and vava umma love you lot dear', "I'll be late...",
       "1's reach home call me.", ..., 'I sent you  &lt;#&gt;  bucks',
       'How much it will cost approx . Per month.',
       'God bless.get good sleep my dear...i will pray!'], dtype=object)

In [71]:
type(X_train.values)

numpy.ndarray

In [72]:
v = CountVectorizer()
X_train_cv = v .fit_transform(X_train.values)

In [73]:
X_train_cv

<4457x7700 sparse matrix of type '<class 'numpy.int64'>'
	with 59102 stored elements in Compressed Sparse Row format>

In [74]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
X_train_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
X_train_cv.shape

(4457, 7700)

In [77]:
v.get_feature_names_out()[10:30]

array(['0207', '02072069400', '02073162414', '02085076972', '021', '03',
       '04', '0430', '05', '050703', '0578', '06', '07', '07008009200',
       '07090201529', '07090298926', '07123456789', '0721072',
       '07732584351', '07734396839'], dtype=object)

In [78]:
v.get_feature_names_out()[1000:1050]

array(['app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'appropriate', 'approve', 'approved',
       'approx', 'apps', 'appt', 'appy', 'april', 'aproach', 'apt',
       'aptitude', 'aquarius', 'ar', 'arab', 'arabian', 'arcade',
       'archive', 'ard', 'are', 'area', 'aren', 'arent', 'arestaurant',
       'aretaking', 'areyouunique', 'argentina', 'argh', 'argue',
       'arguing', 'argument', 'arguments', 'arise', 'arises'],
      dtype=object)

In [79]:
v.get_feature_names_out().shape

(7700,)

In [80]:
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [81]:
v.vocabulary_  #word:position

{'umma': 7075,
 'my': 4634,
 'life': 4074,
 'and': 947,
 'vava': 7208,
 'love': 4197,
 'you': 7664,
 'lot': 4184,
 'dear': 2167,
 'll': 4130,
 'be': 1252,
 'late': 3998,
 'reach': 5550,
 'home': 3447,
 'call': 1580,
 'me': 4375,
 'arun': 1070,
 'can': 1603,
 'transfr': 6970,
 'amt': 940,
 'nvm': 4825,
 'going': 3144,
 'to': 6883,
 'wear': 7370,
 'sport': 6359,
 'shoes': 6059,
 'anyway': 991,
 'leh': 4044,
 'this': 6804,
 'message': 4424,
 'is': 3722,
 'free': 2952,
 'welcome': 7403,
 'the': 6763,
 'new': 4725,
 'improved': 3614,
 'sex': 6000,
 'dogging': 2360,
 'club': 1831,
 'unsubscribe': 7127,
 'from': 2987,
 'service': 5987,
 'reply': 5674,
 'stop': 6445,
 'msgs': 4591,
 '150p': 294,
 '18': 310,
 'only': 4907,
 'ok': 4878,
 'lor': 4176,
 'but': 1550,
 'buy': 1555,
 'wat': 7349,
 'al': 881,
 'he': 3341,
 'does': 2354,
 'moan': 4506,
 'at': 1106,
 'if': 3576,
 'thin': 6792,
 'goes': 3139,
 'wrong': 7584,
 'its': 3740,
 'fault': 2753,
 'de': 2162,
 'arguments': 1047,
 'fed': 2766,
 'u

In [82]:
v.get_feature_names_out()[6847]

'tihs'

In [83]:
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [84]:
X_train_np[0:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [85]:
np.where(X_train_np[0]!= 0)

(array([ 947, 2167, 4074, 4184, 4197, 4634, 7075, 7208, 7664], dtype=int64),)

In [86]:
X_train[:4]

105     Umma my life and vava umma love you lot dear
534                                  I'll be late...
2838                         1's reach home call me.
5457                     Arun can u transfr me d amt
Name: Message, dtype: object

In [87]:
X_train_np[0][1928]

0

In [89]:
v.get_feature_names_out()[1928]

'conference'

In [92]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [93]:
X_test_cv = v.transform(X_test)

In [94]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       955\n           1       0.98      0.96      0.97       160\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.98      0.98      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [95]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       955\n           1       0.98      0.96      0.97       160\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.98      0.98      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [ ]:
#by simply using pipeline we could perform above steps.

In [97]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizor', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [99]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizor', CountVectorizer()), ('nb', MultinomialNB())])

In [101]:
y_pred  = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.98      0.96      0.97       160

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

